### ISSUE TITLE
Allowing for YAML header

### ISSUE THREAD

**Issue by christophe-prevotaux** [Fizzadar/Luapress#95]
Hi, 

It would be nice if YAML like below could be inserted in the Markdown but ignore by the renderer, so that a single file could be used to generate PDF as well as the Luapress content ( just an idea):

```yaml
---
something:
  - "a thing"
  - "another thing"
 keyword: "a yaml example"
...
```

This should be possible to have this anywhere within the document (apart from the where the top headers for Luapress are)
